# Generated by Django 4.1.1 on 2022-09-12 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='driver_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.driversettlement'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='fedex_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.fedexsettlement'),
        ),
    ]
