# Generated by Django 4.1.1 on 2022-09-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_cargo_driver_driversettlement_driverxcargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fedexsettlement',
            name='modelsadjust',
        ),
        migrations.AddField(
            model_name='fedexsettlement',
            name='adjust',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='truck',
            name='name',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='truck',
            name='plate',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='truck',
            name='standard_c_link',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='truck',
            name='standard_insurance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
