# Generated by Django 4.1.1 on 2022-09-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_cargo_driver_settlement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverxcargo',
            old_name='shipment',
            new_name='cargo_id',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='shipment',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
