# Generated by Django 4.1.1 on 2022-09-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_cargo_description_alter_cargo_detention_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='driver_id',
            new_name='nickname',
        ),
    ]
